name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  backend:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint backend
        run: yarn run lint
      - name: Typecheck backend
        run: yarn run typecheck
      - name: Build backend
        run: yarn run build

  frontend:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint frontend
        run: yarn run lint
      - name: Typecheck frontend
        run: yarn run typecheck
      - name: Build frontend
        run: yarn run build
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: frontend/build
          retention-days: 2
